db = {
    'electronics': [
        "Apple iPhone 14",
        "Samsung Galaxy S23",
        "Sony WH-1000XM5 Headphones",
        "Dell XPS 13 Laptop",
        "MacBook Air M2",
        "Apple Watch Series 8",
        "Samsung Galaxy Watch 5",
        "Sony PlayStation 5",
        "Microsoft Xbox Series X",
        "Amazon Echo Dot (5th Gen)",
        "Google Nest Hub",
        "Roku Streaming Stick 4K",
        "LG OLED C2 TV",
        "Samsung QLED 8K TV",
        "Canon EOS R5 Camera",
        "Nikon Z6 II Camera",
        "DJI Mini 3 Pro Drone",
        "GoPro Hero 11 Black",
        "Apple AirPods Pro (2nd Gen)",
        "JBL Charge 5 Bluetooth Speaker",
        "Anker PowerCore 26800 Power Bank",
        "Logitech MX Master 3S Mouse",
        "Razer BlackWidow V4 Keyboard",
        "Asus ROG Strix Gaming Laptop",
        "HP Envy 34 All-in-One PC",
        "Western Digital 2TB External SSD",
        "Seagate 4TB Portable Hard Drive",
        "Netgear Nighthawk AX12 Router",
        "TP-Link Deco X60 Mesh WiFi",
        "Philips Hue Smart Bulbs"
    ],
    'sports': [
        "Wilson Evolution Basketball",
        "Nike Phantom Soccer Ball",
        "Spalding NBA Official Game Ball",
        "Adidas Predator Soccer Shoes",
        "Yonex Astrox 99 Pro Badminton Racket",
        "HEAD Graphene 360+ Speed Pro Tennis Racket",
        "Under Armour UA Highlight Football Cleats",
        "Wilson Clash 100 Tennis Racket",
        "Easton Ghost Advanced Fastpitch Bat",
        "Mizuno Wave Rider 26 Running Shoes",
        "Callaway Strata Complete Golf Set",
        "Rawlings Pro Preferred Baseball Glove",
        "Louisville Slugger Meta BBCOR Baseball Bat",
        "Titleist Pro V1 Golf Balls",
        "Bowflex SelectTech 552 Adjustable Dumbbells",
        "NordicTrack Commercial 1750 Treadmill",
        "Garmin Forerunner 955 Smartwatch",
        "Peloton Bike+",
        "Wilson AVP Official Beach Volleyball",
        "Adidas Tiro Training Soccer Ball",
        "Franklin Sports Pickleball Starter Set",
        "STIGA Advantage Table Tennis Table",
        "Champion Sports Lacrosse Ball Set",
        "SKLZ Speed Hurdles Training Set",
        "ProForm Carbon E7 Elliptical",
        "TRX PRO Suspension Trainer",
        "Wilson NCAA Football",
        "Everlast PowerCore Freestanding Heavy Bag",
        "Babolat Pure Drive Tennis Racket",
        "Hoka One One Clifton 9 Running Shoes"
    ]
}